version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5123:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=aish/proxy.py
      - FLASK_RUN_HOST=0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: >
      flask run
